# Generated by Django 4.2.11 on 2024-06-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file_type', models.IntegerField(blank=True, choices=[(-1, 'Unknown'), (0, 'Image'), (1, 'Video'), (2, 'Document')], null=True)),
                ('file_name', models.CharField(max_length=255, verbose_name='File name')),
                ('file_extension', models.CharField(max_length=255, verbose_name='File extension')),
                ('file_size', models.BigIntegerField(verbose_name='File size')),
                ('file', models.FileField(upload_to='uploaded/%Y/%m/%d/', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
